name: Refresh contributors
on:
  schedule:
    # run 12:15am on Sunday
    - cron:  '15 0 * * 0'
  workflow_dispatch:

jobs:
  refresh-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.5

    - name: Refresh contributors.md with new contributors
      id: refresh-contributors
      shell: bash
      env:
        GITHUB_TOKEN: ${{secrets.KEYMAN_SERVER_REPO_ACCESS_PAT}}
        CROWDIN_TOKEN: ${{secrets.CROWDIN_CONTRIBUTORS_TOKEN}}
      run: |
        cd _scripts/contributors
        ./run.sh
